namespace Celeste.Mod.Microlith57Misc.SourceGen;

[Generator]
public class Impl : IIncrementalGenerator {
    private const string AttributeNamespace = "Celeste.Mod.Microlith57Misc.SourceGen.Attributes";
    private const string AttributeName = "GenerateInfoAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        namespace Celeste.Mod.Microlith57Misc.SourceGen.Attributes;

        /// <summary>
        /// Apply this attribute to a class to generate a companion info class.
        /// </summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
        public sealed class GenerateInfoAttribute : System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Inject the attribute declaration into every compilation
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateInfoAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{AttributeNamespace}.{AttributeName}",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetMarkedClassFromAttribute(ctx))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(classDeclarations, static (spc, classes) => {
            if (classes.IsDefaultOrEmpty) return;

            foreach (var classInfo in classes)
                if (classInfo is not null)
                    GenerateInfoClass(spc, classInfo);
        });
    }

    private static MarkedClassInfo? GetMarkedClassFromAttribute(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

        return new MarkedClassInfo(typeSymbol);
    }

    private static void GenerateInfoClass(SourceProductionContext context, MarkedClassInfo classInfo) {
        var namespaceName = classInfo.Namespace;
        var className = classInfo.ClassName;
        var propertyCount = classInfo.PropertyCount;
        var methodCount = classInfo.MethodCount;

        var namespaceDecl = namespaceName.Length > 0 ? $"namespace {namespaceName};\n\n" : string.Empty;
        var typeName = namespaceName.Length > 0 ? $"{namespaceName}.{className}" : className;

        var source = $$"""
            // <auto-generated/>
            #nullable enable

            {{namespaceDecl}}/// <summary>
            /// Auto-generated companion class for <see cref="{{className}}"/>.
            /// Contains compile-time information about the source type.
            /// </summary>
            public static class {{className}}Info {
                /// <summary>The fully-qualified name of the source type.</summary>
                public const string TypeName = "{{typeName}}";

                /// <summary>The simple name of the source type.</summary>
                public const string ClassName = "{{className}}";

                /// <summary>The namespace that contains the source type.</summary>
                public const string Namespace = "{{namespaceName}}";

                /// <summary>The number of public properties on the source type.</summary>
                public const int PropertyCount = {{propertyCount}};

                /// <summary>The number of public methods on the source type.</summary>
                public const int MethodCount = {{methodCount}};

                /// <summary>Returns a human-readable summary of the source type.</summary>
                public static string GetSummary() =>
                    $"Type: {TypeName}, Properties: {PropertyCount}, Methods: {MethodCount}";
            }
            """;

        context.AddSource($"{className}Info.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private sealed record MarkedClassInfo(INamedTypeSymbol TypeSymbol) {
        public string Namespace { get; } = TypeSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : TypeSymbol.ContainingNamespace.ToDisplayString();

        public string ClassName { get; } = TypeSymbol.Name;

        public int PropertyCount { get; } = TypeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Count(p => p.DeclaredAccessibility == Accessibility.Public);

        public int MethodCount { get; } = TypeSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Count(m => m.DeclaredAccessibility == Accessibility.Public
                            && m.MethodKind == MethodKind.Ordinary);
    }
}
