package.path = "?.lua;selene/selene/lib/?.lua;selene/selene/lib/?/init.lua;../Source/Loenn/libraries/?.lua;../Source/?.lua;" .. package.path

local selene = require("selene")
selene.load(nil, true)

local serialize = require("utils.serialize").serialize

---@diagnostic disable-next-line: missing-fields
mu = {} ---@type mu

---@class mu.preprocess
---@field self Info?
---@field planned_moves {[string]: PlannedMove?}
---@field feature {name: string, defer: (fun():nil)[]}?
---@field lang Lang
local preprocess = {
  configuration = "release",
  dryrun = false,
  timer = false,
  dump = false,
}

mu.preprocess = preprocess

local env_prefix = "MICROLITH57_MISC_"

local env_configuration = os.getenv(env_prefix .. "CONFIGURATION") or mu.preprocess.configuration
mu.preprocess.configuration = env_configuration == "release" and "release" or "debug"
mu.configuration = mu.preprocess.configuration; mu[mu.configuration] = true

local env_dryrun = os.getenv(env_prefix .. "DRYRUN") or "false"
if env_dryrun == "true" then mu.preprocess.dryrun = true end

local env_timer = os.getenv(env_prefix .. "TIMER") or "false"
if env_timer == "true" then mu.preprocess.timer = true end

local env_dump = os.getenv(env_prefix .. "DUMP") or "false"
if env_dump == "true" then mu.preprocess.dump = true end

function mu.library(lib)
  require("mu_" .. lib)
end

require("mu")

---

local function run(cmd)
  if mu.preprocess.dryrun then
    print(cmd)
    return
  end

  local res = io.popen(cmd)
  if not res then error("failed to read output of command: " .. cmd) end
  res:read("*a")
  res:close()
end

---

local lua_header = [[
-- this file is automatically generated, please don't edit it!
-- instead, see the original version at:
--   Source/%s
-- in the source repo.
--
-- for the most part this should be the same as the source, but there may be some differences.
-- see also the preprocess directory (also in the source) for how this happens.

local mu = mu
if not mu then
  mu = require("mods").requireFromPlugin("libraries.mu")
end

]]

local mu_path = "Loenn/libraries/mu.lua"
local mu_header = ([[
-- this file is automatically generated, please don't edit it!
-- instead, see the original version at:
--   Source/%s
-- in the source repo.
--
-- see the preprocess directory (also in the source) for how this happens.

local configuration = "%s"

]]):format(mu_path, mu.configuration)

local lib_header = [[
-- this file is automatically generated, please don't edit it!
-- instead, see the original version at:
--   Source/%s
-- in the source repo.
--
-- see the preprocess directory (also in the source) for how this happens.

return function(mu)
]]
local lib_footer = [[
end
]]

local lang_header = [[
# this file is automatically generated, please don't edit it!
# the language entries here come from many lua files; see the preprocess
# directory in the source for how this happens.

mods.Microlith57MiscellaneousMechanics.name=Microlith57's Misc. Mechanics
]]

---

---@param path string
local function describe_file(path)
  path = path:gsub("^Source/", "")

  for _, excl in ipairs({"bin", "lib", "obj"}) do
    if path:match("^" .. excl) then return nil end
  end

  for _, excl in ipairs({".cs", ".d.lua"}) do
    if path:match(excl .. "$") then return nil end
  end

  local parts = string.split(path, "/")()

  ---@class Info
  ---@field name string  Name of the file, without sigils or extension.
  ---@field ext  string? Extension of the file.
  ---@field feat_path string Path to the feature, including the feature folder itself, relative to `Source`.
  ---@field rel_path  string Path to the file, including the file itself, relative to the feature.
  local info = {
    meta = false,     --- Indicates files that won't be copied to the output. Invoked by the `@` sigil.
    private = false,  --- If true, this file will be skipped in release builds. Invoked by the `_` sigil.
    full_path = path, --- Entire path to the file, including the file itself, relative to `Source`.
  }

  if #parts < 2 then return nil end

  --[[
    a file inside a feature would be:
    > Source/    Entities/ FeatureName/ FeatureName.lua
    > ^discarded ^parts[1] ^parts[2]    ^parts[3]
    >                      ^feature     ^file

    or:
    > Source/   Entities/   A/ B/ C/ FeatureName/ @Inner/   SomethingElse.lua
    >           ^ parts[1]           ^parts[5]    ^parts[6] ^parts[7]
    >                                ^feature               ^file
  ]]

  local feat_path = {} ---@type string[]
  local rel_path = {} ---@type string[]
  for i, part in ipairs(parts) do
    local meta = false

    if part:match("^[@]?[_]") then
      info.private = true
    elseif part:match("^[_]?[@]") then
      meta = true
    end

    local sigilless = part:gsub("^[@_]*", "")

    if i < #parts then
      -- folder
      if meta then
        table.insert(rel_path, part)
      else
        if #rel_path > 0 then
          table.move(rel_path, 1, #rel_path, #feat_path + 1, feat_path)
          rel_path = {}
        end
        table.insert(feat_path, part)

        info.feature = sigilless
      end
    else
      -- file
      info.meta = meta
      info.file = part
      table.insert(rel_path, part)

      ---@param s string
      local function extract_ext(s)
        info.ext = s:drop(1)
        return ""
      end

      info.name = sigilless:gsub("%.[^%.]+$", extract_ext)
    end
  end
  info.feat_path = table.concat(feat_path, "/")
  info.rel_path = table.concat(rel_path, "/")

  return info
end

---@param infos_or_paths (Info|string)[]
local function describe_many(infos_or_paths)
  local by_feature = {} ---@type {[string]: Info[]}

  for _, info in ipairs(infos_or_paths) do
    if type(info) == "string" then
      ---@diagnostic disable-next-line: cast-local-type
      info = describe_file(info)
    end
    if info then
      if by_feature[info.feature] == nil then by_feature[info.feature] = {} end
      table.insert(by_feature[info.feature], info)
    end
  end

  return by_feature
end

local function find_luas(path, infos)
  infos = infos or {}

  local p = ""
  if path then
    p = path:gsub("\\", "\\\\"):gsub('"', '\"')
    if #p > 0 then p = p .. "/" end
  end

  local arg = ([[shopt -s globstar; cd "../Source"; ls "%s**/*.lua"]]):format(p)
  local a = arg:gsub("\\", "\\\\"):gsub('"', '\"')
  local cmd = ([[bash -c "%s"]]):format(a)

  local res = io.popen(cmd)
  local names = {}
  for name in res:lines() do
    table.insert(names, name)
  end
  table.sort(names)

  for i, name in ipairs(names) do
    local info = describe_file(name)
    if info then table.insert(infos, info) end
  end
  return infos
end

local loenn_dirs = {
  Entities = "entities",
  Triggers = "triggers",
}

local function guess_planned_move()
  local info = mu.preprocess.self
  if not info then error("cannot guess a planned move when no feature is being preprocessed") end

  local path = info.full_path
  local first = path:match("^[^/]*") ---@type string

  if info.full_path == mu_path then
    mu.plan_move_self {path, header = mu_header}
  elseif first == "Loenn" then
    mu.plan_move_self {path, header = lib_header:format(path), footer = lib_footer}
  elseif loenn_dirs[first] then
    local dst = table.concat({"Loenn", loenn_dirs[first], info.feature, info.rel_path}, "/")
    mu.plan_move_self {dst, header = lua_header:format(path)}
  end
end

local permitted_destinations = {
  ["Loenn/"] = true,
  ["Graphics/"] = true,
}

local function apply_planned_moves()
  for from, move in pairs(mu.preprocess.planned_moves) do
    local to = move.to
    if not to then goto continue end

    local first_seg = to:match("^%a+/")
    if not first_seg then error("invalid path " .. tostring(to)) end
    if not permitted_destinations[first_seg] then error("illegal destination " .. tostring(first_seg) .. " in " .. tostring(to)) end
    if first_seg:match("/%.%./") then error("illegal .. in " .. tostring(to)) end

    local fa = from:gsub("\\", "\\\\"):gsub('"', '\"')
    local ta = to:gsub("\\", "\\\\"):gsub('"', '\"')

    local tf = ta:gsub("/[^/]+$", "")
    local mkdirp = ([[mkdir -p "../%s"]]):format(tf)
    run(mkdirp)

    local ext = from:match(".%a+$")
    if ext == ".lua" then
      if mu.preprocess.dryrun then
        print(("copy lua from %s to %s"):format(from, to))
      else
        local src = io.open("../Source/" .. from, "r")
        local dst = io.open("../" .. to, "w")

        if move.header then dst:write(move.header) end
        dst:write(src:read("*a"))
        if move.footer then dst:write(move.footer) end

        src:close()
        dst:close()
      end
    else
      local cp = ([[cp "../Source/%s" "../%s"]]):format(fa, ta)
      run(cp)
    end

    ::continue::
  end
end

---@param infos Info[]
local function preprocess_feature(infos)
  local t_start = mu.preprocess.timer and os.clock()

  local exemplar = infos[1]
  local luas = find_luas(exemplar.feat_path)

  if mu.configuration == "release" then
    local any_public = false
    for _, info in ipairs(luas) do
      if not info.private then
        any_public = true
        break
      end
    end
    if not any_public then return end
  end

  mu.preprocess.feature = {
    name = exemplar.feature,
    defer = {},
  }
  mu.preprocess.planned_moves = {}

  -- TODO: make this a bit cleaner
  if mu.preprocess.dump then
    run("mkdir -p ../tmp")
  end
  for _, info in ipairs(luas) do
    if mu.configuration ~= "release" or not info.private then
      mu.preprocess.self = info
      if not info.meta then guess_planned_move() end

      local path = info.full_path:gsub(".lua$", "")
      local res = require(path)
      -- mu.pp(res, "res")

      local _, ser = serialize {result = res}

      if mu.preprocess.dump then
        local f = io.open("../tmp/" .. info.file .. ".dump", "w")
        f:write(ser)
        f:close()
      end
    end
  end

  for _, f in ipairs(mu.preprocess.feature.defer) do
    f()
  end

  apply_planned_moves()

  mu.preprocess.self = nil
  mu.preprocess.feature = nil
  mu.preprocess.planned_moves = nil

  if mu.preprocess.timer then
    local t_end = os.clock()
    local duration = t_end - t_start
    print(("%s: %.4fs"):format(exemplar.feature, duration))
  end
end

local function preprocess_features(by_feature)
  local t_start = mu.preprocess.timer and os.clock()

  mu.preprocess.lang = mu.lang {}

  local features = table.keys(by_feature)
  table.sort(features)
  for _, feature in ipairs(features) do
    preprocess_feature(by_feature[feature])
  end

  run("mkdir -p ../Loenn/lang")
  local f = io.open("../Loenn/lang/en_gb.lang", "w")
  f:write(lang_header)
  mu.print_lang(mu.preprocess.lang, f)
  f:close()

  if mu.preprocess.timer then
    local t_end = os.clock()
    local duration = t_end - t_start
    print(("Processed all features in %.4fs"):format(duration))
  end
end

local luas = {}
--find_luas("DecalRegistry", luas)
find_luas("Entities", luas)
find_luas("Triggers", luas)
find_luas("Loenn", luas)

local by_feature = describe_many(luas)
preprocess_features(by_feature)
