package.path = "?.lua;selene/selene/lib/?.lua;selene/selene/lib/?/init.lua;../Source/Loenn/libraries/?.lua;../Source/?.lua;" .. package.path

local selene = require("selene")
selene.load(nil, true)

local serialize = require("utils.serialize").serialize

mu = {
  preprocess = {
    incremental = false,
    dryrun = false,
    timer = true,
    feature = {},
    lang = nil,
    everestignore = nil,
    planned_moves = nil,
  }
}

local env_prefix = "MICROLITH67_MISC_"

local env_configuration = os.getenv(env_prefix .. "CONFIGURATION") or "release"
mu.configuration = env_configuration == "release" and "release" or "debug"
mu[mu.configuration] = true

local env_incremental = os.getenv(env_prefix .. "INCREMENTAL") or "false"
if env_incremental == "true" then
  mu.preprocess.incremental = true
end

local env_dryrun = os.getenv(env_prefix .. "DRYRUN") or "false"
if env_dryrun == "true" then
  mu.preprocess.dryrun = true
end

local env_timer = os.getenv(env_prefix .. "TIMER") or "false"
if env_timer == "true" then
  mu.preprocess.timer = true
end

require("mu")

---

local function run(cmd)
  if mu.preprocess.dryrun then
    print(cmd)
    return
  end

  local res = io.popen(cmd)
  res:read("*a")
  res:close()
end

---

local lua_header = [[
-- this file is automatically generated, please don't edit it!
-- instead, see the original version at:
--   Source/%s
-- in the source repo.
--
-- for the most part this should be the same as the source, but there may be some differences.
-- see also the preprocess directory (also in the source) for how this happens.

if not mu then
  local mods = require("mods")
  local mu = mods.requireFromPlugin("libraries.utils")
end

]]

local mu_footer = ([[
mu.configuration = "%s"
]]):format(mu.configuration)

local lang_header = [[
# this file is automatically generated, please don't edit it!
# the language entries here come from many lua files; see the preprocess
# directory in the source for how this happens.

mods.Microlith57MiscellaneousMechanics.name=Microlith57's Misc. Mechanics
]]

---

local function describe_file(path)
  if type(path) == "table" then mu.pp(path) end
  path = path:gsub("^Source/", "")

  for _, excl in ipairs({"bin", "lib", "obj"}) do
    if path:match("^" .. excl) then return nil end
  end

  for _, excl in ipairs({".cs"}) do
    if path:match(excl .. "$") then return nil end
  end

  local parts = string.split(path, "/")()

  local info = {
    meta = false,
    private = false,

    full_path = parts,
    feat_path = {},
    feature = nil,
    rel_path = {},
    file = nil,
    name = nil,
    ext = nil,
  }

  if #parts < 2 then return nil end

  --[[
    a file inside a feature would be:
    > Source/    Entities/ FeatureName/ FeatureName.lua
    > ^discarded ^parts[1] ^parts[2]    ^parts[3]
    >                      ^feature     ^file

    or:
    > Source/   Entities/   A/ B/ C/ FeatureName/ @Inner/   SomethingElse.lua
    >           ^ parts[1]           ^parts[5]    ^parts[6] ^parts[7]
    >                                ^feature               ^file
  ]]

  local feat_path = {}
  local rel_path = {}
  for i, part in ipairs(parts) do
    local meta = false

    if part:match("^[@]?[_]") then
      info.private = true
    elseif part:match("^[_]?[@]") then
      meta = true
    end

    local sigilless = part:gsub("^[@_]*", "")

    if i < #parts then
      -- folder
      if not meta then
        feat_path = {}
        for j=1, i do
          feat_path[j] = parts[j]
        end

        info.feature = sigilless
        rel_path = {}
      else
        table.insert(rel_path, part)
      end
    else
      -- file
      info.meta = meta
      info.file = part
      table.insert(rel_path, part)

      local function extract_ext(s)
        info.ext = s:drop(1)
        return ""
      end

      info.name = sigilless:gsub("%.[^%.]+$", extract_ext)
    end
  end
  info.feat_path = table.concat(feat_path, "/")
  info.rel_path = table.concat(rel_path, "/")

  return info
end

local function describe_many(infos_or_paths)
  local by_feature = {}

  for _, info in ipairs(infos_or_paths) do
    if type(path) == "string" then
      info = describe_file(info)
    end
    if info then
      if by_feature[info.feature] == nil then by_feature[info.feature] = {} end
      table.insert(by_feature[info.feature], info)
    end
  end

  return by_feature
end

local function find_luas(path, infos)
  infos = infos or {}

  local p = ""
  if path then
    p = path:gsub("\\", "\\\\"):gsub('"', '\"')
    if #p > 0 then p = p .. "/" end
  end

  local arg = ([[shopt -s globstar; cd "../Source"; ls "%s**/*.lua"]]):format(p)
  local a = arg:gsub("\\", "\\\\"):gsub('"', '\"')
  local cmd = ([[bash -c "%s"]]):format(a)

  local res = io.popen(cmd)
  local names = {}
  for name in res:lines() do
    table.insert(names, name)
  end
  table.sort(names)

  for i, name in ipairs(names) do
    local info = describe_file(name)
    if info then table.insert(infos, info) end
  end
  return infos
end

local loenn_dirs = {
  Entities = "entities",
  Triggers = "triggers",
}

local function guess_planned_move()
  local info = mu.preprocess.self
  local first = info.full_path[1]

  if first == "Loenn" then
    mu.plan_move_self {info.full_path}
  elseif loenn_dirs[first] then
    local dst = table.concat({"Loenn", loenn_dirs[first], info.feature, info.rel_path}, "/")
    mu.plan_move_self {dst}
  end
end

local permitted_destinations = {
  ["Loenn/"] = true,
  ["Graphics/"] = true,
}

local function apply_planned_moves()
  for from, move in pairs(mu.preprocess.planned_moves) do
    local to = move.to

    local first_seg = to:match("^%a+/")
    if not first_seg then error("invalid path " .. tostring(to)) end
    if not permitted_destinations[first_seg] then error("illegal destination " .. tostring(first_seg) .. " in " .. tostring(to)) end
    if first_seg:match("/%.%./") then error("illegal .. in " .. tostring(to)) end

    local fa = from:gsub("\\", "\\\\"):gsub('"', '\"')
    local ta = to:gsub("\\", "\\\\"):gsub('"', '\"')

    local tf = ta:gsub("/[^/]+$", "")
    local mkdirp = ([[mkdir -p "../%s"]]):format(tf)
    run(mkdirp)

    local ext = from:match(".%a+$")
    if ext == ".lua" then
      if mu.preprocess.dryrun then
        print(("copy lua from %s to %s"):format(from, to))
      else
        local src = io.open("../Source/" .. from, "r")
        local dst = io.open("../" .. to, "w")

        if move.header ~= false then
          dst:write(lua_header:format(from))
        end
        dst:write(src:read("*a"))

        src:close()
        dst:close()
      end
    else
      local cp = ([[cp "../Source/%s" "../%s"]]):format(fa, ta)
      run(cp)
    end
  end
end

local function apply_everestignore()
  mu.pp(mu.preprocess.everestignore)
end

local function preprocess_feature(infos)
  local t_start = mu.preprocess.timer and os.clock()
  
  local exemplar = infos[1]
  local luas = find_luas(exemplar.feat_path)

  if mu.configuration == "release" then
    local any_public = false
    for _, info in ipairs(luas) do
      if not info.private then
        any_public = true
        break
      end
    end
    if not any_public then return end
  end

  mu.preprocess.feature = {
    name = exemplar.feature,
    defer = {},
  }
  mu.preprocess.planned_moves = {}
  mu.preprocess.everestignore = {}
  mu.preprocess.lang = mu.lang {}

  for _, info in ipairs(luas) do
    if mu.configuration ~= "release" or not info.private then
      mu.preprocess.self = info

      if not info.meta then guess_planned_move(info) end

      local path = table.concat(info.full_path, "/"):gsub(".lua$", "")
      local res = require(path)
      -- mu.pp(res, "res")

      local _, ser = serialize {result = res}
      local f = io.open("../tmp/" .. info.file, "w")
      f:write(ser)
      f:close()
    end
  end

  for _, f in ipairs(mu.preprocess.feature.defer) do
    f()
  end

  apply_planned_moves()
  -- apply_everestignore()

  -- mu.print_lang(mu.preprocess.lang)

  mu.preprocess.self = nil
  mu.preprocess.feature = nil
  mu.preprocess.planned_moves = nil
  mu.preprocess.everestignore = nil

  if mu.preprocess.timer then
    local t_end = os.clock()
    local duration = t_end - t_start
    print(("%s: %.4fs"):format(exemplar.feature, duration))
  end
end

local function preprocess_features(by_feature)
  local t_start = mu.preprocess.timer and os.clock()

  local features = table.keys(by_feature)
  table.sort(features)
  for _, feature in ipairs(features) do
    preprocess_feature(by_feature[feature])
  end
  
  if mu.preprocess.timer then
    local t_end = os.clock()
    local duration = t_end - t_start
    print(("Processed all features in %.4fs"):format(duration))
  end
end

local luas = {}
--find_luas("DecalRegistry", luas)
--find_luas("Entities", luas)
find_luas("Triggers", luas)

local by_feature = describe_many(luas)
preprocess_features(by_feature)
