name: build (release)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Everest stripped lib
      uses: robinraju/release-downloader@v1.4
      with:
        repository: EverestAPI/Everest
        latest: true
        fileName: lib-stripped.zip

    - name: Extract lib-stripped.zip
      run: unzip lib-stripped.zip

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      env:
        CelestePrefix: ${{ github.workspace }}/lib-stripped

    - name: Unzip again (jank)
      run: |
        mkdir artifact
        unzip Microlith57MiscellaneousMechanics.zip -d artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Microlith57MiscellaneousMechanics
        path: artifact/*
